name: 'issue-task-parser'
description: 'Parse and return tasks contained in a specific issue.'
author: 'TakahashiIkki'

# Define your inputs here.
inputs:
  repo_token:
    description: |-
      Token used to authenticate with GitHub API. Default is built-in token but a personal access token may be used for organization or user projects.
    required: false
    default: ${{ github.token }}

  tag:
    required: true
    description: The tag for previous issue.

# Define your outputs here.
outputs:
  previousIssue:
    description: 'Previous Issue number'
  issueBody:
    description: 'Issue Body'

runs:
  using: node20
  main: dist/index.js
