name: 'previous-issue-finder'
description: 'Retrieves the content of the latest Issue with the specified label.'
author: 'TakahashiIkki'

# Define your inputs here.
inputs:
  repo_token:
    description: |-
      Token used to authenticate with GitHub API. Default is built-in token but a personal access token may be used for organization or user projects.
    required: false
    default: ${{ github.token }}

  label:
    required: true
    description: The label for previous issue.

# Define your outputs here.
outputs:
  previousIssue:
    description: 'Previous Issue number'
  issueBody:
    description: 'Issue Body'

runs:
  using: node20
  main: dist/index.js
