name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main
      - "releases/*"

permissions:
  contents: read # for read release
  issues: read

jobs:
  test-javascript:
    name: JavaScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest
    env:
      LC_ALL: "ja_JP.UTF-8"
      TZ: "Asia/Tokyo"
    strategy:
      matrix:
        label:
          [
            task,
            日報,
          ]

    steps:
      - name: ja_JP.UTF-8
        run: |
          sudo locale-gen ja_JP.UTF-8
          sudo update-locale LANG=ja_JP.UTF-8

      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          label: ${{ matrix.label }}

      - name: Print Output
        id: output
        run:
          echo "${{ steps.test-action.outputs.previousIssue }}"
          echo "${{ steps.test-action.outputs.issueBody }}"
